---
layout: default
title: Transfuse
documentationExpanded: false
postsExpanded: false
---


=== About

Transfuse is a Java Dependency Injection (DI) and integration library geared specifically for the Google Android API.

There are several key features that make Transfuse a great framework to use with Android:

* Dependency Injection - Transfuse implements the http://www.jcp.org/en/jsr/detail?id=330[JSR-330] standard annotations
* POJO Components - Transfuse gives users the ability to develop Android components in Plain Old Java Objects (POJO), enabling a testable, decoupled and flexible style.
* Compile Time Code Generation - Transfuse is remarkably small, lightweight and fast due to the technique of generating supporting code at compile time.
* Manifest Management - Transfuse manages the Android Manifest, eliminating the duplicated effort of declaring and registering components.

All of these features help eliminate boilerplate plumbing code and make Android applications much easier to write.

=== Example

Using Transfuse, an Android Activity looks like the following:

[source,java]
--
@Activity(label = "@string/app_name")
@Layout(R.layout.main) // <4>
public class HelloTransfuse { // <1> 

    @Inject @View(R.id.textview) // <3>
    private TextView textView;

    @Inject @Resource(R.string.hello)
    private String helloText;

    @OnCreate // <2>
    public void hello() {
        textView.setText(helloText);
    }
}
--


<1> Now, Activities no longer extend the android.app.Activity class.
<2> The Android Activity lifecycle is handled via lightweight events.  Any component within the injection graph may define event methods to be called during those phases of the lifecycle.
<3> All specialty injections, such as injecting View elements, are designated with qualifier injections (@View, @Resource, etc.).
<4> Activity Manifest metadata, such as the label, are now defined on the class level instead of the AndroidManifest.xml file.  This puts all the relevant information regarding the Activity in one place.  Transfuse handles the job of registering the Activity and all the associated metadata in the AndroidManifest.xml file.

Read more about the features in the link:documentation.html[Documentation] section.

New to the library or Android? Visit the link:getting_started.html[Getting Started] section.

=== Download

Try Transfuse by downloading from http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.androidtransfuse%22[Maven Central],

via git:

[source]
--
git clone git@github.com:johncarl81/transfuse.git
--

or via Maven:

[source,xml]
--
<dependency>
    <groupId>org.androidtransfuse</groupId>
    <artifactId>transfuse</artifactId>
    <version>{{site.currentVersion}}</version>
    <scope>provided</scope>
</dependency>
<dependency>
    <groupId>org.androidtransfuse</groupId>
    <artifactId>transfuse-api</artifactId>
    <version>{{site.currentVersion}}</version>
</dependency>
--
