---
layout: default
title: Generated Parcelables
shortTitle: Parcels
documentationExpanded: false
comments: true
postsExpanded: true
excerpt: One of my favorite rough spots in Android to rag on is the Parcelable.  Parcelable classes are used by Android as a high-performance serialization option, especially useful when passing data between Activities/Contexts.  What is so rough about Parcelable classes are the API requirements.  Yes, Parcelable is an interface that defines the contract, but Android expects more!
root: ../../../
---

=== Transfuse Technical Blog

==== Generated Parcelables
_January 29, 2013_

One of my favorite rough spots in Android to rag on is the Parcelable.  Parcelable classes are used by Android as a high-performance serialization option, especially useful when passing data between Activities/Contexts.  What is so rough about Parcelable classes are the API requirements.  Yes, Parcelable is an interface that defines the contract, but Android expects more!  Android requires that if your class is a Parcelable (and you're using it as such) then you have to define a:

[source,java]
public static final Parcelable.Creator<MyParcelable> CREATOR


within your class.  The consequences of not doing so is an Exception at run time.  Yes, it must be a Parcelable.Creator, and yes it must be named C-R-E-A-T-O-R.  In addition to this implementing Parcelable is error prone.  You must implement mirrored +createFromParcel()+ and +writeToParcel()+ methods.  Because of this, bugs will often crop up around ordering or missing a field in the implemented Parcelable.

Transfuse gives you a way out of this mess.  Annotating a POJO with +@Parcel+ will trigger, at compile time, the generation of a Parcelable class that serializes using the coordinated Java Bean getters and setters.  The result is your POJO is clear of any Parcelable cruft, while you get the performance of using the Parcelable.  Here's an example:

[source,java]
--
@Parcel
public void CleanParcel{
    private String value;
    public String getValue(){
        return value;
    }
    public void setValue(String value){
        this.value = value;
    }
}
--

Clean, isn't it?

To wrap your `@Parcel` manually, there is a `Parcels` utility class in the API:

[source,java]
Parcelable exampleWrapped = Parcel.wrap(example);

Of course, since it is generated code, you may use it directly as well:

[source,java]
Parcelable exampleWrapped = new ParcelExample_Parcelable(example);

Also, Transfuse will automatically use the generated Parcelable when your `@Parcel` class is referenced in `@Extras`. This affects both the serialization through the generated Intent Factories and the serialization in the receiving Activity/Context.  The end result is you don't even have to bother with wrapping/unwrapping or, of course, implementing the Parcelable.

There are a couple other details that you can read about in the http://androidtransfuse.org/documentation.html#parcel[@Parcel documentation][1].

Here are a few other community solutions/proposals to address the issues around implementing Parcelable classes:

 - http://dallasgutauckis.com/2012/01/20/parcelabler-for-implementing-androids-parcelable-interface/

 - https://github.com/excilys/androidannotations/issues/301

 - https://github.com/foxykeep/parcelablecodegenerator

